# Generated by Django 2.2.5 on 2019-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobrecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.IntegerField(max_length=100)),
                ('s_provider', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
    ]
