# Generated by Django 2.2.5 on 2019-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refno', models.IntegerField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='drecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.IntegerField(max_length=100)),
                ('s_provider', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_bal', models.IntegerField(max_length=100)),
                ('ad_money', models.IntegerField(max_length=100)),
            ],
        ),
    ]
