# Generated by Django 2.2.5 on 2019-11-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_complaints_drecharge_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='refno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drecharge',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drecharge',
            name='cardno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mobrecharge',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mobrecharge',
            name='mob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ad_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='c_bal',
            field=models.IntegerField(),
        ),
    ]
