# Generated by Django 2.2.5 on 2019-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191121_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='addspdtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
