# Generated by Django 2.2.5 on 2019-11-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_addspdtls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addspdtls',
            new_name='spweb',
        ),
        migrations.RenameField(
            model_name='spweb',
            old_name='website',
            new_name='we',
        ),
    ]
