# Generated by Django 2.2.5 on 2020-02-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_serviceprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='service_name',
            new_name='name',
        ),
    ]
