# Generated by Django 2.2.5 on 2020-02-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userregistration',
        ),
    ]
