# Generated by Django 2.2.5 on 2020-02-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200224_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='uname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
