# Generated by Django 2.2.5 on 2020-03-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200301_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='replay',
        ),
    ]
