# Generated by Django 2.2.5 on 2020-03-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_complaints_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='details',
        ),
    ]
