# Generated by Django 2.2.5 on 2020-03-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_complaints_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='username',
            new_name='uname',
        ),
        migrations.AddField(
            model_name='complaints',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
