# Generated by Django 2.2.5 on 2020-03-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20200302_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='replay',
            field=models.TextField(blank=True),
        ),
    ]
