# Generated by Django 2.2.5 on 2020-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_complaints_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='spuname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
