# Generated by Django 2.2.5 on 2020-03-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_complaints_spuname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='spuname',
            new_name='spname',
        ),
    ]
