# Generated by Django 2.2.5 on 2020-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200303_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='replay',
            field=models.TextField(),
        ),
    ]
