# Generated by Django 2.2.5 on 2020-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20200303_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(max_length=100)),
                ('ofr_dtls', models.CharField(max_length=200)),
            ],
        ),
    ]
