# Generated by Django 2.2.5 on 2020-03-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='spname',
            new_name='suname',
        ),
    ]
