# Generated by Django 2.2.5 on 2020-03-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20200306_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='suname',
        ),
    ]
