# Generated by Django 2.2.5 on 2020-03-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_remove_offer_suname'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='spname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
