# Generated by Django 2.2.5 on 2020-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_offer_spname'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
