# Generated by Django 2.2.5 on 2020-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_offer_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobrecharge',
            name='fname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobrecharge',
            name='uname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
