# Generated by Django 2.2.5 on 2020-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20200308_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='drecharge',
            name='fname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drecharge',
            name='uname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
