# Generated by Django 2.2.5 on 2020-03-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_mobrecharge_spname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobrecharge',
            name='spname',
        ),
    ]
