# Generated by Django 2.2.5 on 2020-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_remove_mobrecharge_spname'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('service_no', models.IntegerField()),
                ('s_provider', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='drecharge',
        ),
        migrations.DeleteModel(
            name='mobrecharge',
        ),
    ]
