# Generated by Django 2.2.5 on 2020-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_recharge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
