# Generated by Django 2.2.5 on 2020-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
