# Generated by Django 2.2.5 on 2020-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_remove_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
