# Generated by Django 2.2.5 on 2020-03-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_recharge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
