# Generated by Django 2.2.5 on 2020-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20200318_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
