# Generated by Django 2.2.5 on 2020-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_auto_20200318_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
