# Generated by Django 2.2.5 on 2020-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_auto_20200318_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date_com',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
