# Generated by Django 2.2.5 on 2020-03-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_auto_20200318_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='date_com',
        ),
    ]
