# Generated by Django 2.2.5 on 2020-03-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_remove_complaints_date_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date_com',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
