# Generated by Django 2.2.5 on 2020-03-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_complaints_date_com'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='date_com',
        ),
    ]
