# Generated by Django 2.2.5 on 2020-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_remove_complaints_date_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
