# Generated by Django 2.2.5 on 2020-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
