# Generated by Django 2.2.5 on 2020-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_auto_20200328_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='stat',
        ),
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
