# Generated by Django 2.2.5 on 2020-03-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_auto_20200328_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='status',
        ),
    ]
