# Generated by Django 2.2.5 on 2020-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0047_remove_complaints_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='sta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
