# Generated by Django 2.2.5 on 2020-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0049_auto_20200328_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.TextField(),
        ),
    ]
